### ISSUE TITLE
Issues on CPUs caused by differentiation between CPUs and GPUs

### ISSUE THREAD

**Issue by haesleinhuepf** [ClearControl/clearcl#13]
Hey guys,

I recently had issues with failing createImage() calls because of these lines:

https://github.com/ClearVolume/ClearCL/blob/master/src/java/clearcl/ClearCLContext.java#L321-L323

Apparently, imageChannelOrder must always be ImageChannelOrder.R . Is there an example where the opposite fails? Why do we have a differentiation here in any case?

If there is no reason for having this differentiation, I would replace these three lines with "ImageChannelOrder.R"...

Cheers,
Robert

**Comment by royerloic** [comment]
That's a amd versus intel versus nvidia issue. Use the createimage function that automatically figures out channels...

**Comment by royerloic** [comment]
> Hey guys,
> 
> I recently had issues with failing createImage() calls because of these lines:
> 
> https://github.com/ClearVolume/ClearCL/blob/master/src/java/clearcl/ClearCLContext.java#L321-L323
> 
> Apparently, imageChannelOrder must always be ImageChannelOrder.R . Is there an example where the opposite fails? Why do we have a differentiation here in any case?
> 
on some intel cards this is necessary...
> If there is no reason for having this differentiation, I would replace these three lines with "ImageChannelOrder.R"...
> 
please don't that would break ClearCl on many systems. For some reason it is different on your system. We might need to run a test, catch an exception and act accordingly... So if anything we need to make these lines more complicated unfortunately...

cheers,

Loic

**Comment by royerloic** [comment]
@haesleinhuepf : still an issue? if not let's close this...

**Comment by haesleinhuepf** [comment]
I didn't meet the issue recently. In fact, I always use ImageChannelOrder.R. Thus, on all systems here it works fine like this. I'll close the issue for now.

**Comment by haesleinhuepf** [comment]
Ha! I need to reopen it! E.g. I get an error here:
https://github.com/ClearControl/clearcl/blob/master/src/test/java/clearcl/io/test/ClearCLIOTests.java#L54

clearcl.exceptions.OpenCLException: OpenCL error: -10 -> CL_IMAGE_FORMAT_NOT_SUPPORTED

	at clearcl.backend.BackendUtils.checkOpenCLErrorCode(BackendUtils.java:352)
	at clearcl.backend.jocl.ClearCLBackendJOCL.getImagePeerPointer(ClearCLBackendJOCL.java:457)
	at clearcl.ClearCLContext.createImage(ClearCLContext.java:453)
	at clearcl.ClearCLContext.createImage(ClearCLContext.java:413)
	at clearcl.io.test.ClearCLIOTests.testTiffWriter(ClearCLIOTests.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

If I replace ImageChannelOrder.Intensity with ImageChannelOrder.R it passes that line. I guess that has something to do with my platform: I'm working on Intel i7-8650U / Windows x64. I believe there are some driver/OpenCL-version issues with the built in HD card:
Device name: Intel(R) UHD Graphics 620, type: GPU, OpenCL version: 2.00000 
 max global memory: 6795783373 
 max local memory: 65536 
 clock freq: 1150Mhz 
 nb compute units: 24 
 extensions: cl_intel_accelerator cl_intel_advanced_motion_estimation cl_intel_d3d11_nv12_media_sharing cl_intel_device_side_avc_motion_estimation cl_intel_driver_diagnostics cl_intel_dx9_media_sharing cl_intel_media_block_io cl_intel_motion_estimation cl_intel_planar_yuv cl_intel_packed_yuv cl_intel_required_subgroup_size cl_intel_simultaneous_sharing cl_intel_subgroups cl_intel_subgroups_short cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_depth_images cl_khr_dx9_media_sharing cl_khr_fp16 cl_khr_fp64 cl_khr_gl_depth_images cl_khr_gl_event cl_khr_gl_msaa_sharing cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_gl_sharing cl_khr_icd cl_khr_image2d_from_buffer cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_khr_spir cl_khr_subgroups cl_khr_throttle_hints
