### ISSUE TITLE
RGC broken (under Linux)

### ISSUE THREAD

**Issue by psteinb** [ClearControl/clearcl#25]
Hi,
we've been trying to hunt a memory leak under Linux the past 2 days. We were able to observe the memory leak under Ubuntu and Fedora. 
Today, I was able to observe it as well in [ClearCLRGCTests.java](https://github.com/ClearControl/clearcl/blob/master/src/test/java/clearcl/test/ClearCLRGCTests.java). Under Linux, the ICD runtime environment offers to set a environment variable called `OCL_ICD_DEBUG` in order to print OpenCL function call traces to the terminal. For details, see [here](https://github.com/OCL-dev/ocl-icd/blob/master/doc/libOpenCL.7.txt.in#L97). So I did that and ran the aforementioned tests:

```
$ export OCL_ICD_DEBUG=4
$ ./gradlew clean test --tests \*testRGC > testRGC_ocl-icd_debug.log 2>&1 
```
[testRGC_ocl-icd_debug.log](https://github.com/ClearControl/clearcl/files/2746012/testRGC_ocl-icd_debug.log)

It turns out that the function calls for creating and releasing objects in iteration 2 of this loop already start missing out on releasing images, buffers and more. It's intriguing to see that the test passes, while the ocl-icd trace suggests, only in iteration 1, resources are really cleaned up and released. The aforementioned test consumes up to 13G of memory on my machine. Unfortunately, I don't know similar tools on Windows to cross-check it there.
Best,
P

**Comment by haesleinhuepf** [comment]
Hey @royerloic ,

I was just digging into this issue and have the suspicion that it's related to some class in coremem:

References are added to a list:
https://github.com/ClearControl/coremem/blob/master/src/main/java/coremem/rgc/RessourceCleaner.java#L54

But taken from a queue:
https://github.com/ClearControl/coremem/blob/master/src/main/java/coremem/rgc/RessourceCleaner.java#L77

However, the queue never gets something added and thus, this is always null:
https://github.com/ClearControl/coremem/blob/master/src/main/java/coremem/rgc/RessourceCleaner.java#L80

Could this cause issues when opening/closing CLContexts repeatedly?

Thanks!

Cheers,
Robert

**Comment by royerloic** [comment]
The JVM is actually adding to that queue -- that's how you can get notified right after an object is garbage collected. It is a bit complicated and confusing at first. A very short summary is that this is the 'right' way to do 'finalisation' in Java.  I will not try to explain the details it here. Instead you can check this article:

https://dzone.com/articles/finalization-and-phantom 

I still don't understand why the RGC tests are broken on your side ;-(

**Comment by royerloic** [comment]
Ohh.. make sure you are using the latest coremem, otherwise the rgc tests in clearcl will fail! But before you spend time of that let me finish the review I am doing of that code... Been quite busy, sorry...

**Comment by haesleinhuepf** [comment]
Hey @royerloic ,

I'm afraid, it doesn't help. I just downloaded the coremem source from github master and built it. Afterwards, I pulled clearcl from github master and run the test again. It fails on my Ryzen 3700U with a Vega 10 (8 GB shared GPU mem), Win10 x64 with this error:

```
gfx902
stress test iteration: 0
stress test iteration: 1
stress test iteration: 2
clearcl.exceptions.OpenCLException: OpenCL error: -6 -> CL_OUT_OF_HOST_MEMORY
	at clearcl.backend.BackendUtils.checkOpenCLErrorCode(BackendUtils.java:352)
	at clearcl.backend.jocl.ClearCLBackendJOCL.lambda$getQueuePeerPointer$13(ClearCLBackendJOCL.java:309)
	at clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:156)
	at clearcl.backend.jocl.ClearCLBackendJOCL.getQueuePeerPointer(ClearCLBackendJOCL.java:297)
	at clearcl.ClearCLContext.createQueue(ClearCLContext.java:111)
	at clearcl.test.ClearCLAllocationStressTests.allocateQueues(ClearCLAllocationStressTests.java:151)
	at clearcl.test.ClearCLAllocationStressTests.testWithBackend(ClearCLAllocationStressTests.java:104)
	at clearcl.test.ClearCLAllocationStressTests.testRGC(ClearCLAllocationStressTests.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.fail(Assert.java:64)
	at clearcl.test.ClearCLAllocationStressTests.testWithBackend(ClearCLAllocationStressTests.java:124)
	at clearcl.test.ClearCLAllocationStressTests.testRGC(ClearCLAllocationStressTests.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code -1
```

**Comment by haesleinhuepf** [comment]
Hey @royerloic,

good news! I don't see the bug anymore on my NVidia 1070  system! 🎉 

Have you tried increasing the number of iterations on your system with the Vega GPU?

Thanks!

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Hey @royerloic ,

I was testing it a bit more in detail in my clij-clearcl fork. Unfortunately, I must report that there is apparently still a memory leak somewhere - and help tracing it would be appreciated. Not-cleanable objects are accumulating as suggested by [this tracer](https://github.com/clij/clij-coremem/blob/tracing_memory_leak/src/main/java/net/haesleinhuepf/clij/coremem/rgc/RessourceCleaner.java#L138) and even [shutting down the thread ](https://github.com/clij/clij-coremem/blob/tracing_memory_leak/src/main/java/net/haesleinhuepf/clij/coremem/rgc/RessourceCleaner.java#L156)doesn't help. When running the JMH based benchmarking, I get this output and crash report:

```
Iteration   9: Cleaning 16881(false)
Cleaning 17437(false)
Cleaning 17994(false)
Cleaning 18561(false)
Cleaning 19128(false)
Cleaning 19715(false)
Cleaning 20261(false)
Cleaning 20829(false)
Cleaning 21395(false)
Cleaning 21963(false)
705323.282 ns/op
Iteration  10: Cleaning 22488(false)
Cleaning 23055(false)
Cleaning 23642(false)
Cleaning 24163(false)
Cleaning 24692(false)
Cleaning 25239(false)
Cleaning 25094(false)
Shutting down
Trying to clean the rest
730461.688 ns/op
<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 25 seconds more...>

Non-finished threads:

Thread[pool-2-thread-1,5,main]
  at sun.misc.Unsafe.park(Native Method)
  at java.util.concurrent.locks.LockSupport.park(Unknown Source)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
  at java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
  at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.lang.Thread.run(Unknown Source)

Thread[DestroyJavaVM,5,main]
```

I would speculate, that [this queue](https://github.com/clij/clij-coremem/blob/tracing_memory_leak/src/main/java/net/haesleinhuepf/clij/coremem/rgc/RessourceCleaner.java#L76) is full of not-cleanable stuff. Any idea how to trace it down?

Any hint is appreciated!

Thanks,
Robert

**Comment by haesleinhuepf** [comment]
Another hint: These 25094 objects are `CleaningPhantomReference`s with `get() == null`...

**Comment by haesleinhuepf** [comment]
Ok, I think I found a workaround: I counted the objects being registered and those being cleaned by the resource cleaner. [After finishing up, there are some left](https://github.com/clij/clij-coremem/commit/0e84751a6ad1f0335b0c410da060dfd892af685b#diff-291f10cd17a5d02722f05d1c062635d2R187):

```
Shutting down
Trying to clean the rest
net.haesleinhuepf.clij.clearcl.ClearCLContext: 0
net.haesleinhuepf.clij.clearcl.ClearCLBuffer: 89139
net.haesleinhuepf.clij.clearcl.ClearCLQueue: 0
net.haesleinhuepf.clij.clearcl.ClearCLKernel: 4456
net.haesleinhuepf.clij.clearcl.ClearCLCompiledProgram: 0
673369.987 ns/op
<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 24 seconds more...>
```

Thus, a (not-very-good) workaround is [not collecting kernels, images and buffers anymore](https://github.com/clij/clij-coremem/commit/9e4c39b8e7fcb2d5b3977a9539455e9254ea4b2a#diff-291f10cd17a5d02722f05d1c062635d2R55). 

@royerloic : My conclusion is: **When using coremem - nobody is allowed to call close() methods himself**. CLIJ takes care of cleaning kernels and buffers. Could that be the source of the error? How can we prevent that in the future? Should every close method unregister itself from coremem? What do you think?

Thanks!

Cheers,
Robert

**Comment by royerloic** [comment]
Hi Robert,

A few preliminary observations from what you showed:

(i) The offending thread is not coming from RGC, the name does not match. It comes from a a thread pool: 'pool-2-thread-1,5,main' but we have our own thread with a different name. So that thread that stays alive must come from somewhere else...

(ii) The queue fills up and that's perfectly normal, but I think what is happening is that the 'cleaning' frequency is not high enough or the low priority of the thread might be an issue. If we generate objects faster that it can clean that will cause trouble. The garbage collector might also have issues  keeping up. This would explain why on  some machines it works and other not: differences in allocation speed etc...

**Comment by haesleinhuepf** [comment]
I try to make a minimum example for you. A starting point: In this test, some objects are closed, some others are not. I just print out the number of objects to be cleaned by the end of the outer loop. After iteration 5, the GC should run. But the number keeps increasing:
https://github.com/ClearControl/clearcl/blob/065aa4cfb241dbd8dde776b8abd63beebf84e048/src/test/java/clearcl/test/ClearCLAllocationStressTests.java#L115

```
"C:\Program Files\Java\jdk1.8.0_202\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1\lib\idea_rt.jar=59439:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1\plugins\junit\lib\junit-rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1\plugins\junit\lib\junit5-rt.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\rt.jar;C:\structure\code\clearcl\out\test\classes;C:\structure\code\clearcl\out\test\resources;C:\structure\code\clearcl\out\production\classes;C:\structure\code\clearcl\out\production\resources;C:\Users\rober\.gradle\caches\modules-2\files-2.1\net.clearcontrol\coremem\0.4.8\edb4ba22594982f952646b609fc2707c0d4cbb67\coremem-0.4.8.jar;C:\Users\rober\.m2\repository\com\nativelibs4java\javacl\1.0.0-RC4\javacl-1.0.0-RC4.jar;C:\Users\rober\.m2\repository\org\jocl\jocl\2.0.1\jocl-2.0.1.jar;C:\Users\rober\.m2\repository\javax\vecmath\vecmath\1.5.2\vecmath-1.5.2.jar;C:\Users\rober\.gradle\caches\modules-2\files-2.1\ome\formats-api\5.5.3\18dddd426af2e38a1f94d5b6b4571f5137d694e9\formats-api-5.5.3.jar;C:\Users\rober\.gradle\caches\modules-2\files-2.1\ome\formats-bsd\5.5.3\b88ab769fe36bc8990c17a5d9f3343867212aa5b\formats-bsd-5.5.3.jar;C:\Users\rober\.m2\repository\junit\junit\4.12\junit-4.12.jar;C:\Users\rober\.m2\repository\com\nativelibs4java\bridj\0.7.0\bridj-0.7.0.jar;C:\Users\rober\.m2\repository\net\java\dev\jna\jna\4.5.1\jna-4.5.1.jar;C:\Users\rober\.m2\repository\net\java\dev\jna\jna-platform\4.5.1\jna-platform-4.5.1.jar;C:\Users\rober\.m2\repository\com\nativelibs4java\javacl-core\1.0.0-RC4\javacl-core-1.0.0-RC4.jar;C:\Users\rober\.gradle\caches\modules-2\files-2.1\org.openmicroscopy\ome-xml\5.5.4\e8a0ab41ed684be791dfa8eaeb4fac711d27255a\ome-xml-5.5.4.jar;C:\Users\rober\.m2\repository\org\slf4j\slf4j-api\1.7.6\slf4j-api-1.7.6.jar;C:\Users\rober\.gradle\caches\modules-2\files-2.1\xalan\serializer\2.7.2\24247f3bb052ee068971393bdb83e04512bb1c3c\serializer-2.7.2.jar;C:\Users\rober\.gradle\caches\modules-2\files-2.1\xalan\xalan\2.7.2\d55d3f02a56ec4c25695fe67e1334ff8c2ecea23\xalan-2.7.2.jar;C:\Users\rober\.gradle\caches\modules-2\files-2.1\ome\jai_imageio\5.5.3\1a7c500452334897a2fd26635ed6bdb928bcd913\jai_imageio-5.5.3.jar;C:\Users\rober\.m2\repository\org\openmicroscopy\specification\5.5.4\specification-5.5.4.jar;C:\Users\rober\.gradle\caches\modules-2\files-2.1\ome\turbojpeg\5.5.3\99f67c08c69e620c0ef9902b6f1933467065e460\turbojpeg-5.5.3.jar;C:\Users\rober\.m2\repository\org\scijava\native-lib-loader\2.1.4\native-lib-loader-2.1.4.jar;C:\Users\rober\.m2\repository\com\jgoodies\jgoodies-forms\1.7.2\jgoodies-forms-1.7.2.jar;C:\Users\rober\.m2\repository\com\esotericsoftware\kryo\kryo\2.24.0\kryo-2.24.0.jar;C:\Users\rober\.m2\repository\org\perf4j\perf4j\0.9.13\perf4j-0.9.13.jar;C:\Users\rober\.m2\repository\com\google\guava\guava\17.0\guava-17.0.jar;C:\Users\rober\.m2\repository\com\drewnoakes\metadata-extractor\2.6.2\metadata-extractor-2.6.2.jar;C:\Users\rober\.m2\repository\com\nativelibs4java\opencl4java\1.0.0-RC4\opencl4java-1.0.0-RC4.jar;C:\Users\rober\.m2\repository\com\nativelibs4java\nativelibs4java-utils\1.6\nativelibs4java-utils-1.6.jar;C:\Users\rober\.gradle\caches\modules-2\files-2.1\org.openmicroscopy\ome-common\5.3.1\b686f6333dc195501f881f0791f867a2834130e\ome-common-5.3.1.jar;C:\Users\rober\.gradle\caches\modules-2\files-2.1\joda-time\joda-time\2.2\a5f29a7acaddea3f4af307e8cf2d0cc82645fd7d\joda-time-2.2.jar;C:\Users\rober\.m2\repository\xml-apis\xml-apis\1.3.04\xml-apis-1.3.04.jar;C:\Users\rober\.m2\repository\com\jgoodies\jgoodies-common\1.7.0\jgoodies-common-1.7.0.jar;C:\Users\rober\.m2\repository\com\esotericsoftware\minlog\minlog\1.2\minlog-1.2.jar;C:\Users\rober\.m2\repository\org\objenesis\objenesis\2.1\objenesis-2.1.jar;C:\Users\rober\.m2\repository\com\adobe\xmp\xmpcore\5.1.2\xmpcore-5.1.2.jar;C:\Users\rober\.m2\repository\xerces\xercesImpl\2.8.1\xercesImpl-2.8.1.jar;C:\Users\rober\.m2\repository\ch\qos\logback\logback-core\1.1.1\logback-core-1.1.1.jar;C:\Users\rober\.m2\repository\ch\qos\logback\logback-classic\1.1.1\logback-classic-1.1.1.jar;C:\Users\rober\.m2\repository\com\google\android\tools\dx\1.7\dx-1.7.jar;C:\Users\rober\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 clearcl.test.ClearCLAllocationStressTests,testRGC
Aug 05, 2019 6:12:05 PM org.bridj.BridJ log
INFO: Library not found : atiocl64
Aug 05, 2019 6:12:05 PM org.bridj.BridJ log
INFO: Library not found : amdocl64
Aug 05, 2019 6:12:05 PM org.bridj.BridJ log
INFO: Library not found : atiocl32
Aug 05, 2019 6:12:05 PM org.bridj.BridJ log
INFO: Library not found : atiocl
Aug 05, 2019 6:12:05 PM org.bridj.BridJ log
INFO: Library not found : amdocl32
Aug 05, 2019 6:12:05 PM org.bridj.BridJ log
INFO: Library not found : amdocl
Intel(R) UHD Graphics 620
stress test iteration: 0
Number of objects in RC: 100
stress test iteration: 1
Number of objects in RC: 190
stress test iteration: 2
Number of objects in RC: 280
stress test iteration: 3
Number of objects in RC: 370
stress test iteration: 4
Number of objects in RC: 460
stress test iteration: 5
Number of objects in RC: 550
stress test iteration: 6
Number of objects in RC: 640
stress test iteration: 7
Number of objects in RC: 730
stress test iteration: 8
Number of objects in RC: 820
stress test iteration: 9
Number of objects in RC: 910
stress test iteration: 10
Number of objects in RC: 1000
stress test iteration: 11
Number of objects in RC: 1090
stress test iteration: 12
Number of objects in RC: 1180
stress test iteration: 13
Number of objects in RC: 1270
stress test iteration: 14
Number of objects in RC: 1360
stress test iteration: 15
Number of objects in RC: 1450
stress test iteration: 16
Number of objects in RC: 1540
stress test iteration: 17
Number of objects in RC: 1630
stress test iteration: 18
Number of objects in RC: 1720
stress test iteration: 19
[....]
stress test iteration: 59
Number of objects in RC: 5410
stress test iteration: 60
Number of objects in RC: 5500
stress test iteration: 61
Number of objects in RC: 5590
stress test iteration: 62
clearcl.exceptions.ClearCLTooManyContextsException: Too many contexts have been created and not released
	at clearcl.ClearCLDevice.createContext(ClearCLDevice.java:221)
	at clearcl.test.ClearCLAllocationStressTests.allocateContexts(ClearCLAllocationStressTests.java:135)
	at clearcl.test.ClearCLAllocationStressTests.testWithBackend(ClearCLAllocationStressTests.java:103)
	at clearcl.test.ClearCLAllocationStressTests.testRGC(ClearCLAllocationStressTests.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.fail(Assert.java:64)
	at clearcl.test.ClearCLAllocationStressTests.testWithBackend(ClearCLAllocationStressTests.java:125)
	at clearcl.test.ClearCLAllocationStressTests.testRGC(ClearCLAllocationStressTests.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

I'm afraid the RessourceCleaner has issues with us closing our objects ourselfes. Have a look at the `whatsIn()` method in my fork - it helps you tracing down which objects are uncleaned...
https://github.com/clij/clij-coremem/commit/03a985bb19ece6f090f0fee6f30cf6b5849a5a04

Somehow, the GC/RC gets stuck if it hits a reference to an object, we cleaned ourself...

This "stuck" is the thread JMH sees later on. It's a kind of a deadlock....

**Comment by haesleinhuepf** [comment]
Note: Above example crashes after opening 62 Contexts on an Intel HD which has access to 14 GB of shared GPU memory:

```
Available CL backends:
  * net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@757942a1
  * net.haesleinhuepf.clij.clearcl.backend.javacl.ClearCLBackendJavaCL@4a87761d
    Functional backend:net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@4206a205
    Best backend:net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@44a664f2
Used CL backend: net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@2d2e5f00
ClearCL: ClearCLBase [mClearCLBackendInterface=net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@2d2e5f00, mPeerPointer=null]
  Number of platforms:1
  [0] Intel(R) OpenCL
     Number of devices: 2
     Available devices: 
     [0] Intel(R) UHD Graphics 620 
        NumberOfComputeUnits: 24 
        Clock frequency: 1150 
        Version: 2.0 
        Extensions: cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_depth_images cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_image2d_from_buffer cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_intel_subgroups cl_intel_required_subgroup_size cl_intel_subgroups_short cl_khr_spir cl_intel_accelerator cl_intel_media_block_io cl_intel_driver_diagnostics cl_intel_device_side_avc_motion_estimation cl_khr_priority_hints cl_khr_throttle_hints cl_khr_create_command_queue cl_khr_fp64 cl_khr_subgroups cl_khr_il_program cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_intel_planar_yuv cl_intel_packed_yuv cl_intel_motion_estimation cl_intel_advanced_motion_estimation cl_khr_gl_sharing cl_khr_gl_depth_images cl_khr_gl_event cl_khr_gl_msaa_sharing cl_intel_dx9_media_sharing cl_khr_dx9_media_sharing cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_intel_d3d11_nv12_media_sharing cl_intel_simultaneous_sharing  
        GlobalMemorySizeInBytes: 13641453568 
        LocalMemorySizeInBytes: 65536 
        MaxMemoryAllocationSizeInBytes: 4294959104 
        MaxWorkGroupSize: 256 
        Compatible image types: [SignedNormalizedInt8, SignedNormalizedInt16, UnsignedNormalizedInt8, UnsignedNormalizedInt16, SignedInt8, SignedInt16, SignedInt32, UnsignedInt8, UnsignedInt16, UnsignedInt32, HalfFloat, Float]
     [1] Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 
        NumberOfComputeUnits: 8 
        Clock frequency: 1800 
        Version: 2.0 
        Extensions: cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_dx9_media_sharing cl_intel_dx9_media_sharing cl_khr_d3d11_sharing cl_khr_gl_sharing cl_khr_fp64 cl_khr_image2d_from_buffer cl_intel_vec_len_hint  
        GlobalMemorySizeInBytes: 34103635968 
        LocalMemorySizeInBytes: 32768 
        MaxMemoryAllocationSizeInBytes: 8525908992 
        MaxWorkGroupSize: 8192 
        Compatible image types: [SignedNormalizedInt8, SignedNormalizedInt16, UnsignedNormalizedInt8, UnsignedNormalizedInt16, SignedInt8, SignedInt16, SignedInt32, UnsignedInt8, UnsignedInt16, UnsignedInt32, HalfFloat, Float]
Best GPU device for images: Intel(R) UHD Graphics 620
Best largest GPU device: Intel(R) UHD Graphics 620
Best CPU device: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
```
